name: NASA Project CI

on:
  push:
    branches:
      - master
    paths:
      - "NASA-PROJECT/**"
      - '.github/workflows/nasa.yml'
  pull_request:
    branches:
      - master
    paths:
      - "NASA-PROJECT/**"
      - '.github/workflows/nasa.yml'
jobs:
  build:
    env:
      CI: true

    strategy:
      matrix:
        node-version: [20.x, 24.x]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: NASA-PROJECT

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Install client dependencies
        run: npm ci --prefix client

      - name: Install server dependencies
        run: npm ci --prefix server

      - name: Build client
        run: npm run build

      - name: Run tests
        run: npm test
